[package]
name = "rustatus"
version = "0.1.0"
authors = ["Maxwell Anderson <zaechus@pm.me>"]
edition = "2021"

[dependencies]
time = { version = "0.3", features = ["local-offset", "macros", "formatting"] }
